### ISSUE TITLE
Permission denied when writing log file in storage directory

### ISSUE THREAD

**Issue by azemoning** [kudaliar032/dot-dockerize-laravel#19]
## Error log

```
The stream or file "/var/www/html/storage/logs/laravel-2019-07-14.log" could not be opened: failed to open stream: Permission denied

```

**Comment by kudaliar032** [comment]
thx for issue report, to fix that you can change user permission for storage directory. If you a linux user you can use `chown www-data:www-data -R storage` command

**Comment by azemoning** [comment]
thank you very much, it works like a charm!
